# Generated by Django 3.1.7 on 2021-02-23 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('size_of_position_1', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='wielkość etatu na stanowisku 1')),
                ('size_of_position_2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='wielkość etatu nastanowisku 2')),
            ],
            options={
                'verbose_name': 'Etat',
                'verbose_name_plural': 'Etaty',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Stanowisko',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('ST', 'Stacja Paliw'), ('BA', 'Baza Magazynowa')], default='ST', max_length=2)),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('street', models.CharField(max_length=50, verbose_name='Ulica')),
                ('city', models.CharField(max_length=50, verbose_name='Miejscowość')),
                ('postal_code', models.CharField(max_length=8, verbose_name='Kod pocztowy')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Miejsce Pracy',
                'verbose_name_plural': 'Miejsca Pracy',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię i Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'Nadzorca',
                'verbose_name_plural': 'Nadzorcy',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, verbose_name='imię')),
                ('surname', models.CharField(max_length=40, verbose_name='nazwisko')),
                ('sex', models.CharField(choices=[('W', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1, verbose_name='płeć')),
                ('height', models.PositiveSmallIntegerField(verbose_name='wzrost')),
                ('colar', models.PositiveSmallIntegerField(verbose_name='kołnierzyk')),
                ('width_waist', models.PositiveSmallIntegerField(verbose_name='szerokość w pasie')),
                ('body_size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='rozmiar')),
                ('shoe_size', models.PositiveSmallIntegerField(verbose_name='nr buta')),
                ('email', models.EmailField(max_length=254)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.job', verbose_name='praca')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.workplace', verbose_name='miejsce pracy')),
            ],
            options={
                'verbose_name': 'Kierownik',
                'verbose_name_plural': 'Kierownicy',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='position_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_position', to='employees.position', verbose_name='stanowisko pierwsze'),
        ),
        migrations.AddField(
            model_name='job',
            name='position_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_position', to='employees.position', verbose_name='stanowisko drugie'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, verbose_name='imię')),
                ('surname', models.CharField(max_length=40, verbose_name='nazwisko')),
                ('sex', models.CharField(choices=[('W', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1, verbose_name='płeć')),
                ('height', models.PositiveSmallIntegerField(verbose_name='wzrost')),
                ('colar', models.PositiveSmallIntegerField(verbose_name='kołnierzyk')),
                ('width_waist', models.PositiveSmallIntegerField(verbose_name='szerokość w pasie')),
                ('body_size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=2, verbose_name='rozmiar')),
                ('shoe_size', models.PositiveSmallIntegerField(verbose_name='nr buta')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.job', verbose_name='praca')),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.workplace', verbose_name='miejsce pracy')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
