# Generated by Django 3.1.7 on 2021-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_manager_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='chest',
            field=models.PositiveSmallIntegerField(verbose_name='obwód klatki'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='chest',
            field=models.PositiveSmallIntegerField(verbose_name='obwód klatki'),
        ),
    ]
