# Generated by Django 3.1.7 on 2021-02-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nazwa')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.CreateModel(
            name='KindOfClothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nazwa')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Opis')),
                ('months_to_exchange', models.PositiveSmallIntegerField(verbose_name='Czasokres wymiany w miesiącach')),
                ('available_for', models.ManyToManyField(to='employees.Position', verbose_name='Dostęopne dla')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.manufacturer', verbose_name='Producent')),
            ],
            options={
                'verbose_name': 'Rodzaj Ubrania',
                'verbose_name_plural': 'Rodzaje ubrań',
            },
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_to_order', models.BooleanField(default=False)),
                ('ordered', models.DateField(blank=True, null=True)),
                ('received', models.DateField(blank=True, null=True)),
                ('delivered_ok', models.BooleanField(default=False)),
                ('delivered_with_defects', models.BooleanField(default=False)),
                ('not_delivered', models.BooleanField(default=False)),
                ('owned', models.DateField(blank=True, null=True)),
                ('in_use', models.BooleanField(default=False)),
                ('destroyed', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='employees.employee', verbose_name='Pracownik')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='clothes.kindofclothe', verbose_name='Rodzaj')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_in_order', to='orders.order', verbose_name='Zamówienie')),
            ],
            options={
                'verbose_name': 'Ubranie',
                'verbose_name_plural': 'Ubrania pracowników',
                'ordering': ['-ordered'],
            },
        ),
    ]
