# Generated by Django 3.2.2 on 2021-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(default='a', max_length=40, unique=True, verbose_name='Tytuł'),
            preserve_default=False,
        ),
    ]
