# Generated by Django 3.1.7 on 2021-02-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('during_composing', models.BooleanField(default=True, verbose_name='during_composing')),
                ('composed', models.BooleanField(default=False, verbose_name='composed')),
                ('sent_to_supervisor', models.BooleanField(default=False, verbose_name='sent_to_supervisor')),
                ('date_of_sending_to_supervisor', models.DateField(blank=True, null=True, verbose_name='date_of_sending_to_supervisor')),
                ('approved_by_supervisor', models.BooleanField(default=False, verbose_name='approved_by_supervisor')),
                ('sent_to_manufacturer', models.BooleanField(default=False, verbose_name='sent_to_manufacturer')),
                ('date_of_sending_to_manufacturer', models.DateField(blank=True, null=True, verbose_name='date_of_sending_to_manufacturer')),
                ('received_from_manufacturer', models.BooleanField(default=False, verbose_name='received_from_manufacturer')),
                ('date_of_receiving_from_manufacturer', models.DateField(blank=True, null=True, verbose_name='date_of_receiving_from_manufacturer')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.manager', verbose_name='manager')),
                ('place_of_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.workplace', verbose_name='place_of_delivery')),
            ],
            options={
                'verbose_name': 'Zamówienia',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
    ]
